#!/usr/bin/python
# -*- coding: utf-8 -*-

import argparse
import optparse
import sys

from LocalMaxima.subscripts import gaps, minmax, summary
from LocalMaxima.subscripts import align, columns, extract
subscripts = [gaps, minmax, summary, align, columns, extract]
usage = "usage: %prog --inputfile [input file] [options] [args]"
d = "This script is used to modify structures from PDB or CIF files as input."
opt_parser = optparse.OptionParser(usage, description=d)

arg_parser = argparse.ArgumentParser(description=d)
subparsers = arg_parser.add_subparsers()

for s in subscripts:
    s.register_parser(subparsers)

args = arg_parser.parse_args()
if len(sys.argv) > 1:
    args.func(args)
else:
    print("strctr needs arguments to work. Follow it by\n")
    print("gaps, minmax, summary, align, columns or extract.\n")
    print("Type -h or --help right after for instructions.")
